apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-api
  name: rest-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      imagePullSecrets:
      - name: codefresh-generated-docker.io-rest-api-default
      containers:
      - image: dchung1990/rest-api
        name: rest-api
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest-api
  name: rest-api
  namespace: default
spec:
  ports:
  - name : http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rest-api
  sessionAffinity: None
  type: LoadBalancer
